INFO 2025-02-20 14:27:04,699 autoreload Watching for file changes with StatReloader
WARNING 2025-02-20 14:27:53,548 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-02-20 14:28:10,381 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-20 14:28:26,687 basehttp "POST /api/signup HTTP/1.0" 200 0
INFO 2025-02-20 14:32:05,347 autoreload Watching for file changes with StatReloader
WARNING 2025-02-20 14:32:29,938 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-20 14:41:03,741 autoreload Watching for file changes with StatReloader
INFO 2025-02-20 14:50:42,368 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 20:29:40,373 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 20:30:08,919 autoreload Watching for file changes with StatReloader
WARNING 2025-02-23 20:30:20,725 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-23 20:30:41,574 basehttp "POST /api/signup HTTP/1.0" 200 0
INFO 2025-02-23 20:30:53,528 basehttp "POST /api/login HTTP/1.0" 200 0
WARNING 2025-02-23 20:31:03,974 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-23 20:31:32,176 basehttp "POST /api/signup HTTP/1.0" 200 0
INFO 2025-02-23 20:31:44,902 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-02-23 20:32:07,989 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-02-23 20:32:08,050 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:08,070 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-02-23 20:32:11,216 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:11,230 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-02-23 20:32:11,244 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:17,765 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:17,777 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-02-23 20:32:27,226 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:27,245 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-02-23 20:32:34,346 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-02-23 20:32:34,357 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-02-23 21:33:51,486 autoreload Watching for file changes with StatReloader
WARNING 2025-02-23 21:52:33,861 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-02-23 21:53:32,552 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-02-23 21:53:46,876 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-23 22:10:09,067 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 23:05:25,738 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 23:26:13,536 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 23:27:26,822 autoreload Watching for file changes with StatReloader
INFO 2025-02-23 23:30:54,208 autoreload Watching for file changes with StatReloader
INFO 2025-02-24 09:58:13,298 autoreload Watching for file changes with StatReloader
INFO 2025-02-25 17:48:04,669 autoreload Watching for file changes with StatReloader
INFO 2025-02-25 18:30:38,388 autoreload Watching for file changes with StatReloader
INFO 2025-02-26 11:25:44,010 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 11:25:54,036 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-26 11:27:45,622 autoreload Watching for file changes with StatReloader
WARNING 2025-02-26 11:27:58,256 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-27 17:56:29,813 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 17:57:20,715 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 18:27:11,210 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 18:28:22,074 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 18:30:32,194 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 19:32:26,694 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 19:36:16,674 autoreload Watching for file changes with StatReloader
WARNING 2025-02-27 19:36:21,551 basehttp "GET /api/profile HTTP/1.0" 401 32
ERROR 2025-02-27 19:36:35,689 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 19:36:35,691 basehttp "POST /api/signup HTTP/1.0" 500 185159
ERROR 2025-02-27 19:36:46,180 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 19:36:46,181 basehttp "POST /api/signup HTTP/1.0" 500 185424
INFO 2025-02-27 19:39:54,334 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 19:40:41,861 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 19:41:57,601 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:01:40,286 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:02:51,593 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:04:39,414 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:15:38,031 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:16:48,824 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:19:03,392 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:24:01,792 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:26:43,315 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 20:31:48,266 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 21:32:58,029 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 21:36:17,764 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 22:33:19,425 autoreload Watching for file changes with StatReloader
WARNING 2025-02-27 22:34:24,528 basehttp "GET /api/profile HTTP/1.0" 401 32
ERROR 2025-02-27 22:34:45,575 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 22:34:45,577 basehttp "POST /api/signup HTTP/1.0" 500 185235
ERROR 2025-02-27 22:35:05,656 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 22:35:05,658 basehttp "POST /api/signup HTTP/1.0" 500 185500
WARNING 2025-02-27 22:41:37,059 basehttp "GET /api/profile HTTP/1.0" 401 32
ERROR 2025-02-27 22:42:06,497 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 22:42:06,500 basehttp "POST /api/signup HTTP/1.0" 500 186166
ERROR 2025-02-27 22:42:17,426 log Internal Server Error: /api/signup
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/views.py", line 221, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/back/transcendence/user_management/serializers.py", line 41, in to_internal_value
    return super().to_internal_value(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "user_management_customuser" does not exist
LINE 1: SELECT 1 AS "a" FROM "user_management_customuser" WHERE "use...
                             ^

ERROR 2025-02-27 22:42:17,428 basehttp "POST /api/signup HTTP/1.0" 500 186431
INFO 2025-02-27 22:46:37,947 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 22:53:23,478 autoreload Watching for file changes with StatReloader
INFO 2025-02-27 23:02:43,919 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:01:21,399 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:13:11,379 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:16:21,768 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:19:23,918 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:23:08,106 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:26:40,869 autoreload Watching for file changes with StatReloader
INFO 2025-02-28 09:30:30,680 autoreload Watching for file changes with StatReloader
WARNING 2025-02-28 09:30:36,172 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-02-28 09:30:52,829 basehttp "POST /api/signup HTTP/1.0" 200 0
WARNING 2025-02-28 09:30:58,425 basehttp "POST /api/login HTTP/1.0" 400 39
INFO 2025-02-28 09:31:24,103 basehttp "POST /api/resetpass HTTP/1.0" 200 30
INFO 2025-03-02 21:56:48,926 autoreload Watching for file changes with StatReloader
INFO 2025-03-02 22:18:27,560 autoreload Watching for file changes with StatReloader
WARNING 2025-03-02 22:21:32,621 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:21:50,773 basehttp "POST /api/signup HTTP/1.0" 400 69
INFO 2025-03-02 22:22:04,527 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:22:05,775 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:22:39,802 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:22:39,802 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:22:39,862 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:39,863 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:39,879 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:22:39,894 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:22:42,810 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:42,829 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:22:42,845 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:44,695 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:44,709 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:22:46,205 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:46,219 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:22:46,234 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:49,358 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:22:49,374 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:26:30,293 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:26:30,305 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:26:31,335 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:26:31,352 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:26:31,366 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:26:34,401 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:26:34,416 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
WARNING 2025-03-02 22:26:39,128 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-03-02 22:26:51,021 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:27:02,683 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:27:02,740 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:02,755 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:04,151 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:04,165 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:04,179 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:09,969 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:09,983 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:12,565 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:12,581 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:12,595 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:43,767 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:43,782 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:45,422 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:27:45,435 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:27:45,451 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:06,499 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:06,515 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:06,529 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:09,614 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:09,628 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:10,713 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:10,726 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:11,190 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:11,202 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:11,497 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:11,511 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
WARNING 2025-03-02 22:29:16,366 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-03-02 22:29:27,550 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:29:28,846 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:29:46,168 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:29:46,170 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:29:46,237 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:46,238 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:46,253 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:46,265 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:47,829 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:29:47,843 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:29:47,856 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:30:00,971 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:30:01,033 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:30:04,364 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:30:04,379 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:30:04,397 basehttp "GET /api/profile HTTP/1.0" 200 291
WARNING 2025-03-02 22:31:05,273 basehttp "GET /api/edit-profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:31:31,227 basehttp "GET /api/edit-profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:31:33,537 basehttp "GET /api/edit-profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:31:40,584 basehttp "GET /api/edit-profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:31:46,980 basehttp "GET /api/edit-profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:32:01,706 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:32:04,103 basehttp "GET /api/profiles HTTP/1.0" 401 32
WARNING 2025-03-02 22:32:06,479 basehttp "GET /api/profiles HTTP/1.0" 401 32
WARNING 2025-03-02 22:32:33,075 basehttp "GET /api/profile HTTP/1.0" 401 32
WARNING 2025-03-02 22:32:51,314 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-03-02 22:33:12,027 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:33:15,227 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:33:15,291 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:33:15,309 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:33:27,807 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:33:27,871 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:33:27,887 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:33:32,730 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:33:32,744 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
WARNING 2025-03-02 22:33:48,307 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-03-02 22:34:04,791 basehttp "POST /api/logout HTTP/1.0" 200 0
INFO 2025-03-02 22:40:27,078 autoreload Watching for file changes with StatReloader
INFO 2025-03-02 22:40:39,916 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:40:41,131 basehttp "POST /api/login HTTP/1.0" 200 0
WARNING 2025-03-02 22:40:50,738 basehttp "POST /api/verify-2fa HTTP/1.0" 400 28
WARNING 2025-03-02 22:40:50,743 basehttp "POST /api/verify-2fa HTTP/1.0" 400 28
INFO 2025-03-02 22:40:51,606 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:41:08,463 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
WARNING 2025-03-02 22:41:08,463 basehttp "POST /api/verify-2fa HTTP/1.0" 400 28
WARNING 2025-03-02 22:41:08,463 basehttp "POST /api/verify-2fa HTTP/1.0" 400 28
INFO 2025-03-02 22:41:08,497 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:41:08,512 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:41:10,690 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:41:10,704 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:41:10,718 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:43:08,183 autoreload Watching for file changes with StatReloader
INFO 2025-03-02 22:47:46,925 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:47:46,939 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:47:46,962 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:50:47,688 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:50:47,708 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:50:47,733 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:50:51,445 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:50:51,457 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:50:51,474 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:51:56,007 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:51:56,025 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:51:56,040 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:52:58,910 autoreload Watching for file changes with StatReloader
INFO 2025-03-02 22:53:09,682 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:53:27,110 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:53:27,167 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:53:27,183 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:53:29,532 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:53:29,547 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:53:29,564 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:55:28,004 autoreload Watching for file changes with StatReloader
INFO 2025-03-02 22:55:36,555 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-02 22:55:50,163 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-02 22:55:50,214 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:55:50,226 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:55:51,762 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:55:51,774 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:55:51,791 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:55:55,358 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:55:55,372 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:57:13,661 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:57:13,678 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:57:14,622 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:57:14,636 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:57:14,652 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:58:08,927 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:58:08,940 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:58:08,954 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:58:13,733 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:58:13,746 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:58:15,472 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-02 22:58:15,485 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-02 22:58:15,502 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:41:40,655 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 16:44:53,809 autoreload Watching for file changes with StatReloader
WARNING 2025-03-05 16:46:39,686 basehttp "GET /api/profile HTTP/1.0" 401 32
INFO 2025-03-05 16:48:37,374 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-05 16:49:05,295 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-05 16:49:05,323 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:49:05,339 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:49:07,766 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:49:07,779 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:49:07,792 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:49:10,587 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:49:10,600 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:51:19,759 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:51:19,775 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:51:20,495 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:51:20,508 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:51:20,523 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:53:56,107 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:53:56,120 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:53:56,139 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:54:18,362 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:54:18,373 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:54:18,389 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:55:18,968 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:55:18,981 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:55:18,993 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:56:36,748 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:56:36,762 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:56:36,776 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:57:15,469 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 16:57:15,488 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 16:57:15,503 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 18:28:24,957 autoreload /back/transcendence/transcendence/settings.py changed, reloading.
INFO 2025-03-05 18:33:06,520 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:40:32,641 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:43:10,635 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:45:35,641 autoreload /back/transcendence/transcendence/settings.py changed, reloading.
INFO 2025-03-05 18:46:21,740 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:46:30,286 autoreload /back/transcendence/transcendence/settings.py changed, reloading.
INFO 2025-03-05 18:46:30,578 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:46:54,341 autoreload /back/transcendence/transcendence/settings.py changed, reloading.
INFO 2025-03-05 18:46:54,660 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:47:29,541 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:48:21,988 autoreload Watching for file changes with StatReloader
INFO 2025-03-05 18:50:41,874 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 18:50:41,888 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 18:50:41,902 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 18:50:43,500 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 18:50:43,513 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
INFO 2025-03-05 18:50:45,088 basehttp "POST /api/logout HTTP/1.0" 200 0
INFO 2025-03-05 18:50:54,557 basehttp "POST /api/login HTTP/1.0" 200 0
INFO 2025-03-05 18:51:43,678 basehttp "POST /api/verify-2fa HTTP/1.0" 200 0
INFO 2025-03-05 18:51:43,737 basehttp "GET /api/profile HTTP/1.0" 200 291
INFO 2025-03-05 18:51:43,751 basehttp "GET /api/user_avatar HTTP/1.0" 200 7402
